spring:
  profiles:
    active:
    - dev
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/java-helloworld?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
        #时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
        #设置时区
    time-zone: Asia/Chongqing
  servlet:
    #文件上传配置
    multipart:
      #是否支持文件上传
      enabled: true
      #支持文件写入磁盘
      file-size-threshold: 0
      #上传文件的临时目录 
      location: D:\\temp
      #最大支持文件大小
      max-file-size: 10240
      #最大支持请求大小
      max-request-size: 102400
  
        
      

#端口号配置
server:
  port: 8080

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

#32位的随机数
ronconn:
  secret: ${random.value}
  number: ${random.int}
  name: sun hao
  desc: ${ronconn.name} is a domain main


