#32位的随机数
ronconn:
  secret: ${random.value}
  number: ${random.int}
  name: sun hao
  desc: ${ronconn.name} is a domain main

#端口号配置
server:
  port: 8080

spring:
  jackson:
        #时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
        #设置时区
    time-zone: Asia/Chongqing
