spring:
  profiles:
    active:
    - dev
  jackson:
        #时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
        #设置时区
    time-zone: Asia/Chongqing

#端口号配置
server:
  port: 8080

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

#32位的随机数
ronconn:
  secret: ${random.value}
  number: ${random.int}
  name: sun hao
  desc: ${ronconn.name} is a domain main


